# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - xcelerate

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://xcelerate.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_c41fa5d55b0344b28335c860b0a4dde2 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_418f7ceaeb004ea5b320c1683660bd9c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: xcelerate.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_c41fa5d55b0344b28335c860b0a4dde2 }}/xcelerate:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'xcelerate'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e2a46b5319e448f99c73c708cf30eb8b }}
        images: 'xcelerate.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_c41fa5d55b0344b28335c860b0a4dde2 }}/xcelerate:${{ github.sha }}'